# Generated by Django 5.0.6 on 2024-07-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_team_img'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
    ]
