# Generated by Django 5.0.6 on 2024-07-24 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_card_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.card'),
        ),
    ]
